### ISSUE TITLE
Upload multiple files with a glob pattern?

### ISSUE THREAD

**Issue by willhains** [exuanbo/actions-deploy-gist#89]
Is it possible to upload multiple files to a gist using a glob pattern?

Something like this?

```yaml
- uses: actions/checkout@v2
- name: Deploy
  uses: exuanbo/actions-deploy-gist@v1
  with:
    token: ${{ secrets.TOKEN }}
    gist_id: from_your_gist_url
    gist_description: "foos and bars"
    folder_path: ./dist/
    file_path:
    - foo.txt   # relative to folder_path = ./dist/foo.txt
    - bar/*.txt # relative to folder_path = ./dist/bar/*.txt
```
