### ISSUE TITLE
Create a new gist

### ISSUE THREAD

**Issue by willhains** [exuanbo/actions-deploy-gist#90]
Would it be possible to create a new gist, rather than update an existing one?

Something like this:

```yaml
- uses: actions/checkout@v2
- name: Deploy
  id: create-gist
  uses: exuanbo/actions-deploy-gist@v1
  with:
    token: ${{ secrets.TOKEN }}
    # Omit gist_id to create a new gist
    gist_description: "foo bar"
    gist_file_name: foo.bar
    file_path: ./dist/foo.bar
- name: Generate URL
  # Use output `gist_id` to get the created gist
  run: echo "https://some.endpoint.io?gistId=${{steps.create-gist.outputs.gist_id}}.json"
```
